### PR TITLE
fix(Range): Assert that number of columns is an integer

### PR DESCRIPTION
**Pull request by luchinke**
When i try the following methods: `sheet.get_range_from_a1("D2:FG2").get_values()`, sheetfu throws the following error: 
`
    for column in range(0, self.coordinates.number_of_columns):
TypeError: 'float' object cannot be interpreted as an integer
`

Checked further and it seems that in this case, with this range specified, the self.coordinates.number_of_columns variable contains the number '160.0'.

### CODE REVIEW

**Comment by philippe2803** [comment]
Happy to review.
Could you please make the tests pass before I check?

**Comment by luchinke** [comment]
I am now facing this error from the tests: 

`
The verification check for the environment did not pass.
The command "if [ "$BRANCH" == "master" ]; then semantic-release publish; fi" exited with 1.
`
Don't think I can fix that x)

**Comment by philippe2803** [comment]
@luchinke 
@sp-daniel-sanchez 

What is the status of this PR? Should we keep it or close it? As it is now, it can not be merged as the tests are not working.

**Comment by sp-daniel-sanchez** [comment]
Hi @philippe2803, gonna take a look to the semantic release issue and fix the tests asap.

**Comment by jlasky** [comment]
I can replicate this error by having data in columns A:AA, but the problem goes away when there is data in columns A:Z.

```
for column in range(0, self.coordinates.number_of_columns):
..
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by philippe2803** [comment]
I originally thought the tests actually failed, but it's only a problem with the semantic release.
Happy to merge as soon as the semantic release issue is fixed. Can we look into it?

**Comment by SP-alex-muelas** [comment]
It was a bug in the semantic release script, it was not checking if the PR was coming from a fork. I've fixed it in this PR #39.
@luchinke can you close and re-open this PR for the travis job to run again?

**Comment by philippe2803** [comment]
Feel free to merge without my input.

**Pull request merged**
