### PR TITLE
feat(Table): Create panda DataFrame from Table object.

### PR DESCRIPTION
**Pull request by sp-philippe-oger**
Quick method to create a panda dataframe from a Table object.

### CODE REVIEW

**Comment by sp-philippe-oger** [comment]
Not sure how to test it as I need to have panda installed, and we really don't want to install panda for Travis or as a dependency.

**Comment by SP-alex-muelas** [comment]
I'm lacking context for this. What is pd supposed to be? I have the feeling this just gives an execution error.

**Comment by sp-philippe-oger** [comment]
`pd` is the convention for Panda module in python. This may not be appropriate to put that method here, I agree but let's discuss. I think Sheetfu would be more useful for analyst if it offers a bridge to analyst. 

Panda is a python library for data science, that helps you process data in a form of a table. Analysts working in Python uses Panda a lot.

This method is here to create a DataFrame, the core object of panda, from a Sheetfu Table object. Panda is a hardcore library, with plenty of dependencies (Numpy, etc...), so we don't want to add the library as dependency to Sheetu, but instead we add the module as an argument to the function.
For panda user, a very well know convention is to import as follow `import pandas as pd`, so we put pd as an argument, so we don't need to have it as a dependency to Sheetfu.

We could put it somewhere else if needed. I think there is plenty of utils we could add, like import/export to csv or other formats.

**Comment by SP-alex-muelas** [comment]
Oh I see. I didn't know about the existance of Panda. Anyways, if we are doing something like this I strongly feel like it should be documented somewhere like on the Readme.

"Using panda with sheetfu":
To use panda with sheetfu, do import pandas as pd, pip install pandas, pip install numpy etc.

**Comment by sp-philippe-oger** [comment]
Agreed.
After thinking about it, I do not think we should add it there. Let's not merge that PR and leave it on hold for the time being. I need to do some more research on how deep the integration with panda could actually be.

**Pull request closed without merging**
