### PR TITLE
fix(convert_letter_to_column): column_number in int type

### PR DESCRIPTION
**Pull request by GeorgiyDemo**
## The problem
**column_number** was in double type when column's letter was more then “Z” ("AA", "AB", "AC", etc..)
And it was Error:
 ```
File "/usr/local/lib/python3.8/dist-packages/sheetfu/modules/table.py", line 218, in _generate_delete_intitial_items_range_batch
    empty_column_values = [""] * self.items_range.coordinates.number_of_columns
TypeError: can't multiply sequence by non-int of type 'float'
```
in
https://github.com/socialpoint-labs/sheetfu/blob/967700b1920340abfda8930349c51c7841294efb/sheetfu/modules/table.py#L218

That happened when I called table.delete_items

#### Code
```python
from sheetfu import SpreadsheetApp, Table

TABLE_ID = "1FpO1v-SmJYVY22BZTGQ54puW5gwE_MXlx-rFFMZrd_U" 
PATH = "./TEST_JSON.json"

sa = SpreadsheetApp(PATH)
spreadsheet = sa.open_by_id(TABLE_ID)

sheet = spreadsheet.get_sheet_by_name("Sheet1")
table = Table(sheet.get_data_range())

# Select the data
remove_item = table.select([{"name": "George"}])

# Print the type of number_of_columns
print(table.items_range.coordinates.number_of_columns)
print(type(table.items_range.coordinates.number_of_columns))

# Remove the item
table.delete_items(remove_item)
table.commit()
```
#### Output
A-Z:
```
26
<class 'int'>
```

A-AE:
```
31.0
<class 'float'>
Traceback (most recent call last):
  File "/Users/demg/Desktop/TEST_MEM/test.py", line 20, in <module>
    table.delete_items(remove_item)
  File "/usr/local/lib/python3.9/site-packages/sheetfu/modules/table.py", line 133, in delete_items
    return self.delete(indexes_to_delete)
  File "/usr/local/lib/python3.9/site-packages/sheetfu/modules/table.py", line 151, in delete
    self._generate_delete_intitial_items_range_batch()
  File "/usr/local/lib/python3.9/site-packages/sheetfu/modules/table.py", line 218, in _generate_delete_intitial_items_range_batch
    empty_column_values = [""] * self.items_range.coordinates.number_of_columns
```

So, I fixed that

### CODE REVIEW

**Review by philippe2803 — APPROVED** [review]
Good stuff. Thank you.

**Comment by philippe2803** [comment]
@SP-alex-muelas not sure what is going on here. The travis check does not seem to be triggered :-(

**Comment by philippe2803** [comment]
@SP-alex-muelas @sp-jordi-miro  I do not have access to settings anymore. Can anyone look into this bug we're having? https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by SP-alex-muelas** [comment]
Apparently our PR builds were not running (only the branch builds). And since this is a PR from a fork, there is no branch build. I've reset the travis settings & PR builds seem to be running again :D

**Comment by SP-alex-muelas** [comment]
I've also disabled the requirement for branch builds so we can accept PRs from forks like in this case.

**Review by SP-alex-muelas — APPROVED** [review]

**Comment by philippe2803** [comment]
Thanks @SP-alex-muelas !

**Comment by philippe2803** [comment]
@GeorgiyDemo your PR has been merged. Thanks for your input!

**Pull request merged**
